url: http://astokes.org
name: Adam Stokes
description: >
  struck gold, spent it all on amazon, /me
  sad
timezone: Amercia/New_York
permalink: /:title
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
highlighter: rouge
assets:
  compress:
    js: uglifier
    css: sass
exclude: ['bower_components']
paginate: 5